name: Build Template
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"
  push:
    branches: ["*"]
    paths-ignore:
      - "**/docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_NAME: simple-app
      PROJECT_NAME: simple-app-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate project
        uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
          template: ${{ env.TEMPLATE_NAME }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs fail. See https://github.com/rust-lang/cargo/issues/9922
      - name: Check project
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
